// <auto-generated />
using System;
using CooperativaAgropecuaria.web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CooperativaAgropecuaria.web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.Agricultor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamanoCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agricultores");
                });

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.Maquinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgricultorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostoHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId");

                    b.ToTable("Maquinarias");
                });

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.UsoMaquinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgricultorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("HorasUso")
                        .HasColumnType("float");

                    b.Property<Guid>("MaquinariaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId");

                    b.HasIndex("MaquinariaId");

                    b.ToTable("UsosMaquinaria");
                });

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.Maquinaria", b =>
                {
                    b.HasOne("CooperativaAgropecuaria.web.Models.Entities.Agricultor", "Agricultor")
                        .WithMany("Maquinarias")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agricultor");
                });

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.UsoMaquinaria", b =>
                {
                    b.HasOne("CooperativaAgropecuaria.web.Models.Entities.Agricultor", "Agricultor")
                        .WithMany("UsosMaquinaria")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CooperativaAgropecuaria.web.Models.Entities.Maquinaria", "Maquinaria")
                        .WithMany("UsosMaquinaria")
                        .HasForeignKey("MaquinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agricultor");

                    b.Navigation("Maquinaria");
                });

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.Agricultor", b =>
                {
                    b.Navigation("Maquinarias");

                    b.Navigation("UsosMaquinaria");
                });

            modelBuilder.Entity("CooperativaAgropecuaria.web.Models.Entities.Maquinaria", b =>
                {
                    b.Navigation("UsosMaquinaria");
                });
#pragma warning restore 612, 618
        }
    }
}
